apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: demo
  name: flink-fraud-demo
spec:
  image: 074661079081.dkr.ecr.us-west-2.amazonaws.com/flink-job-fraud-demo:v12
  flinkVersion: v1_16
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  mode: native
  job:
    jarURI: local:///opt/flink/usrlib/job.jar
    parallelism: 1
    upgradeMode: stateless
    state: running
